### ISSUE TITLE
Swap background image for slider in Agency template

### ISSUE THREAD

**Issue by jwebandgraphic** [IronSummitMedia/startbootstrap#90]
This is my first time customizing a bootstrap template, and I'm having some styling issues. I've asked for help on stackoverflow and hired someone on Craigslist, but I still don't have a solution. The problem:

I have a client who wants me to swap the background image in Agency for an image slider. I've removed the background properties in agency.css and added the slider to the HTML file. The result is a working slider, but the elements originally positioned above the background image have now been pushed off the slider. I have tried to absolutely position the header and relatively position the slider and the parent element of the elements original stacked on the background image. I also set z indexes to both relatively positioned elements. This breaks styles for the rest of the page. How do I resolve this?

**Comment by davidtmiller** [comment]
I would use a plugin like backstretch to create this sort of effect. Otherwise just keep playing around with the CSS.

**Comment by Dhan-An-Jay** [comment]
facing a problem in bootstrap...... i want to add a background image in web but i failed lot of times....
Please help me...... i have agent.css and there i have background tag and it just doesnt work... i am going through web but i didnt find correct solution... please help me that......
header {
	text-align: center;
	color: #fff;
	background-attachment: scroll;
  background-image: url('../assets/header-bg.jpg');
  background-repeat: no-repeat;
  background-attachment: scroll;
  background-position: center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  text-align: center;
  color: white;





in above code i m adding that header-bg.jpg from assets but it doesnt work.....
what should i do to add background cover in my web page....... what to do in below css statement
background-image: url('../assets/header-bg.jpg');
