### ISSUE TITLE
Modern Business - Carousel won't pause when mouse hovers

### ISSUE THREAD

**Issue by agxii** [IronSummitMedia/startbootstrap#93]
I guess the slider carousel should pause when I hover my mouse over the slides. 
From bootstrap.js file:
 "Carousel.DEFAULTS = {
    interval: 5000,
    pause: 'hover',
    ...
 ...}"

I'm using Google Chrome Version 44.0.2403.125 m and I've also tried this on your preview site just too make sure I haven't messed something up with my changes to your template on my project.

**Comment by davidtmiller** [comment]
Not sure with this one, it looks like it might be a Bootstrap issue rather than something within the template.
